matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "11"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-angular && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: "11"
      jdk: oraclejdk8
      before_install:
        - travis_wait sudo pip install six
        - travis_wait gem install cocoapods
        - travis_wait pod repo update --silent
      script:
        - cd src && npm i
        - cd ../demo && npm i && npm run build.plugin && tns build ios --bundle --env.uglify
        - cd ../demo-angular && npm i && npm run build.plugin && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 11
      script:
        - cd src && npm i
        - cd ../demo && npm i && npm run build.plugin && tns build android --bundle --env.uglify --env.snapshot
        - cd ../demo-angular && npm i && npm run build.plugin && tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env:
        - BuildAndroid="27"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 11
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="11.0"
      osx_image: xcode10
      language: node_js
      node_js: "11"
      jdk: oraclejdk8
      before_install:
        - travis_wait sudo pip install six
        - travis_wait gem install cocoapods
        - travis_wait pod repo update --silent
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - build-tools-28.0.3
    - android-28
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns --version
    - tns usage-reporting disable
    - tns error-reporting disable

before_script:
